Repository geo-knowledge-hub/geo-knowledge-hub-rt, pull requests merged in 2020-08, with the labels that each got.

#14 Add host IP in invenio.cfg
  scripts/aws_after_install.sh
Labels: enhancement, infrastructure

#16 Add a shell script to load GEO Knowledge Hub demo data
  scripts/aws_app_start.sh
  scripts/load-demo-data.sh
Labels: enhancement, infrastructure

#3 pages customization
  assets/less/theme.less
  assets/less/variables.less
  invenio.cfg
  static/images/gkh_frontpage.jpg
  templates/details/my_citation.html
  templates/details/my_contact.html
  templates/details/my_description.html
  templates/details/my_doi.html
  templates/details/my_keywords.html
  templates/details/my_licenses.html
  templates/details/package_components.html
  templates/my_frontpage.html
  templates/my_header_frontpage.html
  templates/my_record_landing_page.html
  templates/my_uploads.html
Labels: release

#18 Add Pipfile.lock to main repository.
  Pipfile.lock
Labels: bug

#17 Improve installation document
  INSTALL.rst
  scripts/before_install.sh
  scripts/install.sh
  scripts/run-tests.sh
Labels: documentation
